/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Conexion;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SARA
 */
public class Formbienvenido extends javax.swing.JFrame {

    /**
     * Creates new form Formbienvenido
     */
    public Formbienvenido() {
        initComponents();
        setLocationRelativeTo(null);
    }
    Conexion cn = new Conexion();
    Connection con; //Verificar la instrucción sql y ejecutarla
    PreparedStatement ps;//Objeto donde se carga el resultado de la consulta
    ResultSet rs; //Objeto que guarda el resultado de la consulta
   public void validarLogin (){ // Método para válidar el inicio de sesión de un usuario registrado.
        boolean ok = false;
        
        try {
            String usuario = TxtUsuario3.getText();//  Devuelve un objeto String como un tipo de dato cadena.
            String password = String.valueOf(clave3.getText());
            
            String sql = "select * from usuarios where Usuario='"+usuario+"' and Contraseña='"+password+"'";
            
            PreparedStatement ps = cn.getConnection().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()){ // Recorre todsa las filas del usuario y del password hasta que se encuentren los datos correctos
                ok = true;
                
                if (ok == true){
                    JOptionPane.showMessageDialog(null, "Correcto");
                    FormMenu frm = new FormMenu();
                    Formbienvenido frmB = new Formbienvenido();
                    frmB.setVisible(false);
                    frm.setVisible(true);
                    this.dispose();
                    
                    //JOptionPane.showMessageDialog(null, "Bienvenido");
                    //FormRegistro2 form = new FormRegistro2(); // Si los datos son correctos se abre la pestaña bienvenido
                    //form.setVisible(true);
                    //this.dispose(); //Cerrar el Form actual cuando el otro se ejecuta después de validar los datos
                    
                }  
            }else {
                    JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectas");
            }
            
                    
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectas" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSalir3 = new javax.swing.JButton();
        btnIngresar3 = new javax.swing.JButton();
        clave3 = new javax.swing.JPasswordField();
        TxtUsuario3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondobienvenido.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSalir3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir72pxbienvenido.png"))); // NOI18N
        btnSalir3.setBorder(null);
        btnSalir3.setBorderPainted(false);
        btnSalir3.setContentAreaFilled(false);
        btnSalir3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir96pxbienvenido.png"))); // NOI18N
        btnSalir3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalir3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalir3MouseExited(evt);
            }
        });
        btnSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 140, 120));

        btnIngresar3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnIngresar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar72.png"))); // NOI18N
        btnIngresar3.setBorder(null);
        btnIngresar3.setBorderPainted(false);
        btnIngresar3.setContentAreaFilled(false);
        btnIngresar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresar3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresargrande.png"))); // NOI18N
        btnIngresar3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIngresar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresar3MouseExited(evt);
            }
        });
        btnIngresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 140, 120));

        clave3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        clave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clave3ActionPerformed(evt);
            }
        });
        jPanel1.add(clave3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 120, 30));

        TxtUsuario3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuario3ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 120, 30));

        jLabel13.setBackground(new java.awt.Color(153, 255, 204));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setText("Contraseña:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Usuario:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, 30));

        jLabel11.setBackground(new java.awt.Color(153, 0, 204));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("INGRESO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel3.setText("¡BIENVENIDO!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondobienvenido.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuario3ActionPerformed

    private void clave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clave3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clave3ActionPerformed

    private void btnIngresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar3ActionPerformed
        validarLogin();
    }//GEN-LAST:event_btnIngresar3ActionPerformed

    private void btnSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir3ActionPerformed
        // Opcion para confirmacion de salida de la ventana. En donde "salIR" es el título de la ventana.
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro que desea salir?", "SALIR",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }//GEN-LAST:event_btnSalir3ActionPerformed

    private void btnSalir3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir3MouseEntered
       btnSalir3.setText("Salir");
    }//GEN-LAST:event_btnSalir3MouseEntered

    private void btnSalir3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir3MouseExited
       btnSalir3.setText(""); 
    }//GEN-LAST:event_btnSalir3MouseExited

    private void btnIngresar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresar3MouseEntered
        btnIngresar3.setText("Ingresar");
    }//GEN-LAST:event_btnIngresar3MouseEntered

    private void btnIngresar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresar3MouseExited
        btnIngresar3.setText("");
    }//GEN-LAST:event_btnIngresar3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formbienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formbienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formbienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formbienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formbienvenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtUsuario3;
    public javax.swing.JButton btnIngresar3;
    public javax.swing.JButton btnSalir3;
    private javax.swing.JPasswordField clave3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
