/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author SARA
 */
public class FormRegistro2 extends javax.swing.JInternalFrame {

    static void main(String[] args) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    /**
     * Creates new form FormRegistro2
     */
    public FormRegistro2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbprimerNombre = new javax.swing.JLabel();
        jLbsegundoNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLbsegundoApellido = new javax.swing.JLabel();
        jLbsexo = new javax.swing.JLabel();
        jLbtipoDocumento = new javax.swing.JLabel();
        jLbndocumento = new javax.swing.JLabel();
        jLbfechaNacimiento = new javax.swing.JLabel();
        jLbedad = new javax.swing.JLabel();
        jLbcoberturaEnsalud = new javax.swing.JLabel();
        jLbprimerNombreacudiente = new javax.swing.JLabel();
        jLbsegundoNombreacudiente = new javax.swing.JLabel();
        jLbprimerApellidoacudiente = new javax.swing.JLabel();
        jLbsegundoApellidoacudiente = new javax.swing.JLabel();
        jLbparentesco = new javax.swing.JLabel();
        jLbdirección = new javax.swing.JLabel();
        jLbsector = new javax.swing.JLabel();
        jLbtelefono = new javax.swing.JLabel();
        jLbobservaciones = new javax.swing.JLabel();
        jTxprimerNombre = new javax.swing.JTextField();
        jTxsegundoNombre = new javax.swing.JTextField();
        jTxsexo = new javax.swing.JTextField();
        jTxsegundoApellido = new javax.swing.JTextField();
        jTxtipoDocumento = new javax.swing.JTextField();
        jTxndocumento = new javax.swing.JTextField();
        jTxedad = new javax.swing.JTextField();
        jTxcoberturaEnsalud = new javax.swing.JTextField();
        jTxprimerNombreacudiente = new javax.swing.JTextField();
        jTxsegundoNombreacudiente = new javax.swing.JTextField();
        jTxprimerApellidoacudiente = new javax.swing.JTextField();
        jTxsegundoApellidoacudiente = new javax.swing.JTextField();
        jTxparentesco = new javax.swing.JTextField();
        jTxdirección = new javax.swing.JTextField();
        jTxsector = new javax.swing.JTextField();
        jTxtelefono = new javax.swing.JTextField();
        jTxobservaciones = new javax.swing.JTextField();
        jLbprimerApellido = new javax.swing.JLabel();
        jDtfechaNacimiento = new com.toedter.calendar.JDateChooser();
        jBtNuevo = new javax.swing.JButton();
        jBtGuardar = new javax.swing.JButton();
        jBtActualizar = new javax.swing.JButton();
        jBtConsultar = new javax.swing.JButton();
        jBtSalir = new javax.swing.JButton();
        jTxprimerApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBtEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setMaximizable(true);
        setResizable(true);
        setTitle("Registro Participantes fundación");
        setMaximumSize(new java.awt.Dimension(1800, 1800));

        jLbprimerNombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbprimerNombre.setText("primer Nombre");

        jLbsegundoNombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbsegundoNombre.setText(" segundo Nombre");

        jLbsegundoApellido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbsegundoApellido.setText("segundo Apellido");

        jLbsexo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbsexo.setText("sexo");

        jLbtipoDocumento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbtipoDocumento.setText("tipo Documento");

        jLbndocumento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbndocumento.setText("ndocumento");

        jLbfechaNacimiento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbfechaNacimiento.setText("fecha Nacimiento");

        jLbedad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbedad.setText("edad");

        jLbcoberturaEnsalud.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbcoberturaEnsalud.setText("cobertura En salud");

        jLbprimerNombreacudiente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbprimerNombreacudiente.setText("primer Nombre acudiente");

        jLbsegundoNombreacudiente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbsegundoNombreacudiente.setText("segundo Nombre acudiente");

        jLbprimerApellidoacudiente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbprimerApellidoacudiente.setText("primer Apellido acudiente");

        jLbsegundoApellidoacudiente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbsegundoApellidoacudiente.setText("segundo Apellido acudiente");

        jLbparentesco.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbparentesco.setText("parentesco");

        jLbdirección.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbdirección.setText("dirección");

        jLbsector.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbsector.setText("sector");

        jLbtelefono.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbtelefono.setText("telefono");

        jLbobservaciones.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbobservaciones.setText("observaciones");

        jTxprimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxprimerNombreActionPerformed(evt);
            }
        });

        jTxsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxsexoActionPerformed(evt);
            }
        });

        jTxparentesco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxparentescoActionPerformed(evt);
            }
        });

        jTxsector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxsectorActionPerformed(evt);
            }
        });

        jTxobservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxobservacionesActionPerformed(evt);
            }
        });

        jLbprimerApellido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLbprimerApellido.setText("primer Apellido");

        jBtNuevo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo72px.png"))); // NOI18N
        jBtNuevo.setBorder(null);
        jBtNuevo.setContentAreaFilled(false);
        jBtNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo96px.png"))); // NOI18N
        jBtNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtNuevoMouseExited(evt);
            }
        });
        jBtNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNuevoActionPerformed(evt);
            }
        });

        jBtGuardar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar72px.png"))); // NOI18N
        jBtGuardar.setToolTipText("");
        jBtGuardar.setBorder(null);
        jBtGuardar.setBorderPainted(false);
        jBtGuardar.setContentAreaFilled(false);
        jBtGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar96px.png"))); // NOI18N
        jBtGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtGuardarMouseExited(evt);
            }
        });
        jBtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGuardarActionPerformed(evt);
            }
        });

        jBtActualizar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtActualizar.setForeground(new java.awt.Color(255, 51, 255));
        jBtActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar72px.png"))); // NOI18N
        jBtActualizar.setBorder(null);
        jBtActualizar.setBorderPainted(false);
        jBtActualizar.setContentAreaFilled(false);
        jBtActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtActualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar96px.png"))); // NOI18N
        jBtActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtActualizarMouseExited(evt);
            }
        });
        jBtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtActualizarActionPerformed(evt);
            }
        });

        jBtConsultar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar72px.png"))); // NOI18N
        jBtConsultar.setBorder(null);
        jBtConsultar.setBorderPainted(false);
        jBtConsultar.setContentAreaFilled(false);
        jBtConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtConsultar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar96px.png"))); // NOI18N
        jBtConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtConsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtConsultarMouseExited(evt);
            }
        });

        jBtSalir.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir72px.png"))); // NOI18N
        jBtSalir.setBorder(null);
        jBtSalir.setContentAreaFilled(false);
        jBtSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir96px.png"))); // NOI18N
        jBtSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtSalirMouseExited(evt);
            }
        });
        jBtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalirActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fundacion_huellas.jpg"))); // NOI18N

        jBtEliminar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar72px.png"))); // NOI18N
        jBtEliminar.setToolTipText("");
        jBtEliminar.setBorder(null);
        jBtEliminar.setBorderPainted(false);
        jBtEliminar.setContentAreaFilled(false);
        jBtEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar72px.png"))); // NOI18N
        jBtEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar96px.png"))); // NOI18N
        jBtEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtEliminarMouseExited(evt);
            }
        });
        jBtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLbsegundoApellido)
                    .addComponent(jLbsexo)
                    .addComponent(jLbtipoDocumento)
                    .addComponent(jLbndocumento)
                    .addComponent(jLbfechaNacimiento)
                    .addComponent(jLbprimerApellido)
                    .addComponent(jLbprimerNombre)
                    .addComponent(jLbsegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbedad, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbcoberturaEnsalud))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxedad)
                    .addComponent(jTxndocumento)
                    .addComponent(jTxtipoDocumento)
                    .addComponent(jTxsegundoNombre)
                    .addComponent(jTxsexo)
                    .addComponent(jDtfechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jTxsegundoApellido)
                    .addComponent(jTxcoberturaEnsalud, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jTxprimerApellido)
                    .addComponent(jTxprimerNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbprimerNombreacudiente)
                    .addComponent(jLbprimerApellidoacudiente)
                    .addComponent(jLbparentesco)
                    .addComponent(jLbdirección)
                    .addComponent(jLbsector)
                    .addComponent(jLbtelefono)
                    .addComponent(jLbobservaciones)
                    .addComponent(jLbsegundoNombreacudiente)
                    .addComponent(jLbsegundoApellidoacudiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTxsector, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jTxdirección, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxparentesco, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxsegundoApellidoacudiente, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxprimerApellidoacudiente, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxsegundoNombreacudiente, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxprimerNombreacudiente, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtelefono, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxobservaciones))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jBtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jBtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jBtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jBtActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jBtGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbprimerNombre)
                            .addComponent(jTxprimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbprimerNombreacudiente)
                            .addComponent(jTxprimerNombreacudiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxsegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbsegundoNombreacudiente)
                            .addComponent(jTxsegundoNombreacudiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbsegundoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLbprimerApellido))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxprimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLbprimerApellidoacudiente)
                                .addComponent(jTxprimerApellidoacudiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLbsegundoApellido))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTxsegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLbsexo)
                                    .addComponent(jTxsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLbparentesco)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLbsegundoApellidoacudiente)
                                    .addComponent(jTxsegundoApellidoacudiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jTxparentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbtipoDocumento)
                            .addComponent(jTxtipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbdirección)
                            .addComponent(jTxdirección, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbndocumento)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxndocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLbsector)
                                .addComponent(jTxsector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDtfechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLbfechaNacimiento))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLbedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLbcoberturaEnsalud)
                                    .addComponent(jTxcoberturaEnsalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLbtelefono)
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTxtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbobservaciones)
                                    .addComponent(jTxobservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jBtGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jBtEliminar.getAccessibleContext().setAccessibleName("");
        jBtEliminar.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void Transparenciabotones(){
          jBtEliminar.setOpaque(false);
          jBtEliminar.setContentAreaFilled(false);
          jBtEliminar.setBorderPainted(false);
}
    private void jTxparentescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxparentescoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxparentescoActionPerformed

    private void jTxsectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxsectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxsectorActionPerformed

    private void jTxobservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxobservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxobservacionesActionPerformed

    private void jTxprimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxprimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxprimerNombreActionPerformed

    private void jBtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtGuardarActionPerformed

    private void jTxsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxsexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxsexoActionPerformed

    private void jBtGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtGuardarMouseEntered
               jBtGuardar.setText("Guardar");
    }//GEN-LAST:event_jBtGuardarMouseEntered

    private void jBtGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtGuardarMouseExited
                  jBtGuardar.setText("");
    }//GEN-LAST:event_jBtGuardarMouseExited

    private void jBtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtSalirActionPerformed

    private void jBtEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtEliminarMouseEntered
                 jBtEliminar.setText(" Eliminar ");
    }//GEN-LAST:event_jBtEliminarMouseEntered

    private void jBtEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtEliminarMouseExited
                jBtEliminar.setText("");
    }//GEN-LAST:event_jBtEliminarMouseExited

    private void jBtNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtNuevoMouseEntered
         jBtNuevo.setText("Nuevo");
    }//GEN-LAST:event_jBtNuevoMouseEntered

    private void jBtNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtNuevoMouseExited
        jBtNuevo.setText("");
    }//GEN-LAST:event_jBtNuevoMouseExited

    private void jBtNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtNuevoActionPerformed

    private void jBtConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtConsultarMouseEntered
         jBtConsultar.setText("Consultar");
    }//GEN-LAST:event_jBtConsultarMouseEntered

    private void jBtConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtConsultarMouseExited
         jBtConsultar.setText("");
    }//GEN-LAST:event_jBtConsultarMouseExited

    private void jBtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtSalirMouseEntered
         jBtSalir.setText("Salir");
    }//GEN-LAST:event_jBtSalirMouseEntered

    private void jBtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtSalirMouseExited
        jBtSalir.setText("");
    }//GEN-LAST:event_jBtSalirMouseExited

    private void jBtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtActualizarActionPerformed

    private void jBtActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtActualizarMouseEntered
        jBtActualizar.setText("Actualizar");
    }//GEN-LAST:event_jBtActualizarMouseEntered

    private void jBtActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtActualizarMouseExited
         jBtActualizar.setText("");
    }//GEN-LAST:event_jBtActualizarMouseExited

    private void jBtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtActualizar;
    public javax.swing.JButton jBtConsultar;
    public javax.swing.JButton jBtEliminar;
    public javax.swing.JButton jBtGuardar;
    public javax.swing.JButton jBtNuevo;
    public javax.swing.JButton jBtSalir;
    public com.toedter.calendar.JDateChooser jDtfechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLbcoberturaEnsalud;
    public javax.swing.JLabel jLbdirección;
    public javax.swing.JLabel jLbedad;
    public javax.swing.JLabel jLbfechaNacimiento;
    public javax.swing.JLabel jLbndocumento;
    public javax.swing.JLabel jLbobservaciones;
    public javax.swing.JLabel jLbparentesco;
    public javax.swing.JLabel jLbprimerApellido;
    public javax.swing.JLabel jLbprimerApellidoacudiente;
    public javax.swing.JLabel jLbprimerNombre;
    public javax.swing.JLabel jLbprimerNombreacudiente;
    public javax.swing.JLabel jLbsector;
    public javax.swing.JLabel jLbsegundoApellido;
    public javax.swing.JLabel jLbsegundoApellidoacudiente;
    public javax.swing.JLabel jLbsegundoNombre;
    public javax.swing.JLabel jLbsegundoNombreacudiente;
    public javax.swing.JLabel jLbsexo;
    public javax.swing.JLabel jLbtelefono;
    public javax.swing.JLabel jLbtipoDocumento;
    public javax.swing.JTextField jTxcoberturaEnsalud;
    public javax.swing.JTextField jTxdirección;
    public javax.swing.JTextField jTxedad;
    public javax.swing.JTextField jTxndocumento;
    public javax.swing.JTextField jTxobservaciones;
    public javax.swing.JTextField jTxparentesco;
    public javax.swing.JTextField jTxprimerApellido;
    public javax.swing.JTextField jTxprimerApellidoacudiente;
    public javax.swing.JTextField jTxprimerNombre;
    public javax.swing.JTextField jTxprimerNombreacudiente;
    public javax.swing.JTextField jTxsector;
    public javax.swing.JTextField jTxsegundoApellido;
    public javax.swing.JTextField jTxsegundoApellidoacudiente;
    public javax.swing.JTextField jTxsegundoNombre;
    public javax.swing.JTextField jTxsegundoNombreacudiente;
    public javax.swing.JTextField jTxsexo;
    public javax.swing.JTextField jTxtelefono;
    public javax.swing.JTextField jTxtipoDocumento;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
